USE [Testing]
GO

/****** Object:  Table [dbo].[REGISTER]    Script Date: 27/04/2015 14:52:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REGISTER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SESSIONID] [nvarchar](50) NOT NULL,
	[IDUSER] [int] NOT NULL,
	[DLOGIN] [datetime] NOT NULL,
	[DLOGOUT] [datetime] NULL,
	[IP] [nvarchar](50) NULL,
	[CONNECT] [bit] NULL,
 CONSTRAINT [PK_REGISTER_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[USERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](50) NOT NULL,
	[PASSWORD] [nvarchar](100) NOT NULL,
	[DOB] [date] NULL,
	[COUNTRY] [nvarchar](50) NULL,
	[AVATAR] [nvarchar](50) NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO